### ISSUE TITLE
Camera crash on iOS with Flutter 3.0.5

### ISSUE THREAD

**Issue by 2math** [Lightsnap/flutter_better_camera#51]
Hi, with version 1.0.1 , 1.0.2 and 1.0.2+1 
when I try to init the camera it crashes the app on iOS. 
This is somehow related to Flutter version 3.0.5, with Flutter 2.10.4 version 1.0.1 worked with no problem.

Thanks in advance!

Here are my Logs :
```
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ 🐛 2022-08-02 13:54:57.384222 DEBUG AppLog CameraBloc : Has flash true
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ 🐛 2022-08-02 13:54:57.385934 DEBUG AppLog CameraBloc : initializeCameraController
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ 🐛 2022-08-02 13:54:57.393566 DEBUG AppLog CameraBloc : cameras [CameraDescription(com.apple.avfoundation.avcapturedevice.built-in_video:0, CameraLensDirection.back, 90), CameraDescription(com.apple.avfoundation.avcapturedevice.built-in_video:1, CameraLensDirection.front, 90)]
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ 🐛 2022-08-02 13:54:57.396570 DEBUG AppLog CameraBloc : PermissionStatus.granted
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ 🐛 2022-08-02 13:54:57.397339 DEBUG AppLog CameraBloc : _initCamera
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[VERBOSE-3:platform_message_handler_ios.mm(106)] Check failed: task_runners_.GetPlatformTaskRunner()->RunsTasksOnCurrentThread().
* thread #37, queue = 'io.flutter.camera.dispatchqueue', stop reason = signal SIGABRT
    frame #0: 0x00000001bba08bbc libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1bba08bbc <+8>:  b.lo   0x1bba08bd8               ; <+36>
    0x1bba08bc0 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1bba08bc4 <+16>: mov    x29, sp
    0x1bba08bc8 <+20>: bl     0x1bba0460c               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.
```

Tested on iPhoneX - iOS 15.4.1

flutter doctor --verbose
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64, locale en-BG)
    • Flutter version 3.0.5 at /Users/galeen/soft/flutter2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/galeen/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/galeen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (3 available)
    • FL iPhone X (mobile) • e698b0ece23b534f74e736ed49046f021c6afe2c • ios            • iOS 15.4.1 19E258
    • macOS (desktop)      • macos                                    • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)         • chrome                                   • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by 2math** [comment]
I'm using in the same project this package https://pub.dev/packages/qr_code_scanner , which loads the camera with no issues on iOS

**Comment by ro0t** [comment]
Fixed in 1.0.3

**Comment by ishaquehassan** [comment]
@ro0t its not working in even 1.0.3

**Comment by mohsinraza-fdev** [comment]
@ro0t Still crashing on ios with same error logs even on 1.0.3
